// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf-Sj7tcfNUCeRaPYmFnb6r3epLh-h3Cw',
    appId: '1:454461850240:web:ce979f6ae072e10bc59c65',
    messagingSenderId: '454461850240',
    projectId: 'alpha-32d98',
    authDomain: 'alpha-32d98.firebaseapp.com',
    storageBucket: 'alpha-32d98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBPVcNIVO03c7pZS6sBVdpwazskEUxULE',
    appId: '1:454461850240:android:7183a2ee34ab86d4c59c65',
    messagingSenderId: '454461850240',
    projectId: 'alpha-32d98',
    storageBucket: 'alpha-32d98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcwUDZPFTlWrMwW6QQBulBVGcrk4XxWsM',
    appId: '1:454461850240:ios:b42456b3f1f61903c59c65',
    messagingSenderId: '454461850240',
    projectId: 'alpha-32d98',
    storageBucket: 'alpha-32d98.appspot.com',
    iosClientId: '454461850240-vtgb2g1nb9jo3m94f9s6i8ucplp0g6uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.mashikur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcwUDZPFTlWrMwW6QQBulBVGcrk4XxWsM',
    appId: '1:454461850240:ios:b42456b3f1f61903c59c65',
    messagingSenderId: '454461850240',
    projectId: 'alpha-32d98',
    storageBucket: 'alpha-32d98.appspot.com',
    iosClientId: '454461850240-vtgb2g1nb9jo3m94f9s6i8ucplp0g6uv.apps.googleusercontent.com',
    iosBundleId: 'com.example.mashikur',
  );
}
